<?php


if ( ! class_exists( 'ACF' ) ) {
  add_action( 'admin_notices', function() {
    echo '<div class="error"><p>ACF5 Pro is not activated. Make sure you activate the plugin in <a href="' . esc_url( admin_url( 'plugins.php' ) ) . '">' . esc_url( admin_url( 'plugins.php' ) ) . '</a></p></div>';
  } );
  return;
}

$passport_brand_id  = get_field('passport_brand_identifier', 'option');

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'promotion_data_capture',
  'title' => 'Promotion',
  'fields' => array (
		array (
			'key' => 'promotion_data_capture_tab',
			'label' => 'Promotion',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
    array (
      'key' => 'field_55c493302cb37',
      'label' => 'Data to capture with email',
      'name' => 'data_to_capture',
      'type' => 'checkbox',
      'instructions' => 'Check any additional data you\'d like to capture from the user',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'fullName' => 'Full Name',
        'address' => 'Address',
        'telephoneNumber' => 'Telephone Number',
        'competition' => 'Competition Answer',

      ),
      'default_value' => array (
        '' => '',
      ),
      'layout' => 'vertical',
    ),
    array (
      'key' => 'promo_data_capture_is_voucher',
      'label' => 'Does this promotion require an emailed voucher?',
      'name' => 'is_voucher',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_55c4938482e93',
      'label' => 'Competition Question',
      'name' => 'competition_question',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_55c493302cb37',
            'operator' => '==',
            'value' => 'competition',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => 'What is the new Burger King burger called?',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_55c4941b82e94',
      'label' => 'Competition Answers',
      'name' => 'competition_answers',
      'type' => 'repeater',
      'instructions' => 'Add your answers',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_55c493302cb37',
            'operator' => '==',
            'value' => 'competition',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'min' => 1,
      'max' => 5,
      'layout' => 'table',
      'button_label' => 'Add Answer',
      'sub_fields' => array (
        array (
          'key' => 'field_55c4944382e95',
          'label' => 'Answer Text',
          'name' => 'answer_text',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_55c4944b82e96',
          'label' => 'Answer Correct',
          'name' => 'answer_correct',
          'type' => 'true_false',
          'instructions' => 'Tick one of these boxes to represent the correct answer',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
        ),
      ),
    ),
    array (
      'key' => 'promo_data_capture_is_voucher',
      'label' => 'Does this promotion require an emailed voucher?',
      'name' => 'is_voucher',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_55c494b1fbf43',
      'label' => 'Collect data for a 3rd party? (Client optins)',
      'name' => 'collect_optins',
      'type' => 'true_false',
      'instructions' => 'Users of this promotion will have opportunity to share their data with a third party',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_55c495f5638ae',
      'label' => 'Third Party Optins',
      'name' => 'third_party_optins',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_55c494b1fbf43',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'min' => 1,
      'max' => 3,
      'layout' => 'row',
      'button_label' => 'Add Optin',
      'sub_fields' => array (
        array (
          'key' => 'field_55c49601638af',
          'label' => 'Optin Name',
          'name' => 'optin_name',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => 'Burger King',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_55c49609638b0',
          'label' => 'Optin Label',
          'name' => 'optin_label',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => 'Would you like to receive updates from Burger King?',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
      ),
    ),
    array (
      'key' => 'field_55c4963f99e59',
      'label' => 'Terms and Conditions Label',
      'name' => 'terms_and_conditions_label',
      'type' => 'text',
      'instructions' => 'Override the terms and conditions label here',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'I accept the terms and conditions',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_55c4966b99e5a',
      'label' => 'Terms and Conditions',
      'name' => 'terms_and_conditions',
      'type' => 'wysiwyg',
      'instructions' => 'Add any promotion specific terms and conditions here',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
    ),
    array (
      'key' => 'field_55cb2873a5e40',
      'label' => 'Start Date & Time',
      'name' => 'start_time',
      'type' => 'date_time_picker',
      'instructions' => 'Choose the time and date that this promotion will start',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'show_date' => 'true',
      'date_format' => 'm/d/y',
      'time_format' => 'h:mm tt',
      'show_week_number' => 'false',
      'picker' => 'slider',
      'save_as_timestamp' => 'true',
      'get_as_timestamp' => 'true',
    ),
    array (
      'key' => 'field_55cb28a7a5e42',
      'label' => 'End Date & Time',
      'name' => 'end_time',
      'type' => 'date_time_picker',
      'instructions' => 'Choose the time and date that this promotion will end',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'show_date' => 'true',
      'date_format' => 'm/d/y',
      'time_format' => 'h:mm tt',
      'show_week_number' => 'false',
      'picker' => 'slider',
      'save_as_timestamp' => 'true',
      'get_as_timestamp' => 'true',
    ),
    array(
      'key' => 'passport_brand_identifier_promo',
      'label' => 'passport_brand_identifier_promo',
      'name' => 'passport_brand_identifier_promo',
      'type' => 'text',
      'instructions' => 'This is the default brand identifier for this site, generally you should not need to change this',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => ''
      ),
      'default_value' => $passport_brand_id,
      'placeholder' => 'Passport Brand Identifier',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 1,
      'disabled' => 1
    ),
    array(
      'key' => 'selected_passport',
      'label' => 'selected_passport',
      'name' => 'selected_passport',
      'type' => 'text',
      'instructions' => 'This is a field for the currently selected passport. If you can see this there is a bug as it should be hidden!',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => ''
      ),
      'default_value' => '',
      'placeholder' => 'selected_passport',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0
    ),
    array (
      'key' => 'promo_passport',
      'label' => 'Promotion Passport',
      'name' => 'promotion_passport',
      'type' => 'select',
      'instructions' => 'We need to save the data for this promotion somewhere. Choose the passport you\'d like to save this data into. If you\'re not sure what Passports are, or have never heard of "Calais", our internal database, then contact a member of the Digital Operations team.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        '' => '',
      ),
      'default_value' => array (
        '' => '',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
		array (
			'key' => 'promotion_data_capture_voucher_tab',
			'label' => 'Voucher',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'promo_data_capture_is_voucher',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'promo_data_capture_template',
			'label' => 'Template',
			'name' => 'template',
			'type' => 'text',
			'instructions' => 'The name of the template to use with this email. Lowercase and no spaces.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'promo_data_capture_email_subject',
			'label' => 'Email Subject',
			'name' => 'email_subject',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'promo_data_capture_brand_header',
			'label' => 'Brand Header Image',
			'name' => 'brand_header',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'promo_data_capture_hero_image',
			'label' => 'Hero Image',
			'name' => 'hero_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'promo_data_capture_heading',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'promo_data_capture_description',
			'label' => 'Description',
			'name' => 'description',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
		),
		array (
			'key' => 'promo_data_capture_voucher_gen_code',
			'label' => 'Automatically generate voucher code',
			'name' => 'generate_code',
      'type' => 'true_false',
      'instructions' => 'Automatically generate a voucher code. Uncheck to manually enter.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 1,
		),
		array (
			'key' => 'promo_data_capture_voucher_code',
			'label' => 'Enter voucher code',
			'name' => 'voucher_code',
			'type' => 'text',
			'instructions' => 'Manually enter a Voucher Code.',
			'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'promo_data_capture_voucher_gen_code',
            'operator' => '!=',
            'value' => 1,
          ),
        ),
      ),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'promo_data_capture_voucher_with_title',
			'label' => 'Include the title from the containing post?',
			'name' => 'include_title',
			'type' => 'true_false',
			'instructions' => 'This allows you to add the title from the post that uses this promotion in the email voucher.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'promo_data_capture_voucher_title_term',
			'label' => 'Enter a one word description of the post title',
			'name' => 'title_term',
      'type' => 'text',
      'instructions' => 'E.g. Enter \'Venue\' if you want to display the following: </br> <b>Venue</b> - Burger and Lobster </br>Leave blank to only display the post title.',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'promo_data_capture_voucher_with_title',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
		),
		array (
			'key' => 'promo_data_capture_voucher_info',
			'label' => 'Other Voucher Information',
			'name' => 'voucher_info',
			'type' => 'wysiwyg',
			'instructions' => 'e.g.<br/>
Valid until: 25/12/2015</br>
Only valid on Tuesday evenings',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
		),
		array (
			'key' => 'promo_data_capture_voucher_terms',
			'label' => 'Voucher Terms and Conditions',
			'name' => 'voucher_terms',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'promo',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
));

endif;
