<?php


if ( ! class_exists( 'ACF' ) ) {
  add_action( 'admin_notices', function() {
    echo '<div class="error"><p>ACF5 Pro is not activated. Make sure you activate the plugin in <a href="' . esc_url( admin_url( 'plugins.php' ) ) . '">' . esc_url( admin_url( 'plugins.php' ) ) . '</a></p></div>';
  } );
  return;
}

if( function_exists('register_field_group') ):


register_field_group(array (
  'key' => 'quiz_definition',
  'title' => 'Quiz Definition',
  'fields' => array (
      array (
          'key' => 'quiz_definition_quiz_type',
          'label' => 'Quiz Type!',
          'name' => 'quiz_type',
          'prefix' => '',
          'type' => 'select',
          'instructions' => 'Score outcome "You scored 15 out of 20!"
          Text outcome "You\'re a Lion Tamer!"',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'choices' => array (
              'score' => 'Score outcome',
              'text' => 'Text outcome',
          ),
          'default_value' => array (
              'score' => 'score',
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 0,
          'ajax' => 0,
          'placeholder' => '',
          'disabled' => 0,
          'readonly' => 0,
      ),
      array (
          'key' => 'quiz_definition_score_bad',
          'label' => 'Score "bad" label',
          'name' => 'score_bad',
          'prefix' => '',
          'type' => 'text',
          'instructions' => 'e.g. "Were you even paying attention? That was next level bad"',
          'required' => 0,
          'conditional_logic' => array (
              array (
                  array (
                      'field' => 'quiz_definition_quiz_type',
                      'operator' => '==',
                      'value' => 'score',
                  ),
              ),
          ),
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'formatting' => 'html',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
      ),
      array (
          'key' => 'quiz_definition_score_okay_label',
          'label' => 'Score "okay" label',
          'name' => 'score_okay_label',
          'prefix' => '',
          'type' => 'text',
          'instructions' => 'e.g. "Okay so you didn’t embarrass yourself"',
          'required' => 0,
          'conditional_logic' => array (
              array (
                  array (
                      'field' => 'quiz_definition_quiz_type',
                      'operator' => '==',
                      'value' => 'score',
                  ),
              ),
          ),
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'formatting' => 'html',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
      ),
      array (
          'key' => 'quiz_definition_score_good_label',
          'label' => 'Score "good" label',
          'name' => 'score_good_label',
          'prefix' => '',
          'type' => 'text',
          'instructions' => 'e.g. Nice going, there could be a career in answering quiz questions ahead of you',
          'required' => 0,
          'conditional_logic' => array (
              array (
                  array (
                      'field' => 'quiz_definition_quiz_type',
                      'operator' => '==',
                      'value' => 'score',
                  ),
              ),
          ),
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'formatting' => 'html',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
      ),
      array (
          'key' => 'quiz_definition_score_excellent',
          'label' => 'Score "excellent" label',
          'name' => 'score_excellent',
          'prefix' => '',
          'type' => 'text',
          'instructions' => 'e.g. "You’re the best! Around! Nothing’s ever going to keep you down!"',
          'required' => 0,
          'conditional_logic' => array (
              array (
                  array (
                      'field' => 'quiz_definition_quiz_type',
                      'operator' => '==',
                      'value' => 'score',
                  ),
              ),
          ),
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'formatting' => 'html',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
      ),
      array (
          'key' => 'quiz_definition_text_outcomes',
          'label' => 'Text outcomes',
          'name' => 'text_outcomes',
          'prefix' => '',
          'type' => 'repeater',
          'instructions' => 'Add various outcomes to the quiz',
          'required' => 1,
          'conditional_logic' => array (
              array (
                  array (
                      'field' => 'quiz_definition_quiz_type',
                      'operator' => '==',
                      'value' => 'text',
                  ),
              ),
          ),
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'row_min' => '',
          'row_limit' => '',
          'layout' => 'table',
          'button_label' => 'Add Outcome',
          'min' => 0,
          'max' => 0,
          'sub_fields' => array (
              array (
                  'key' => 'quiz_definition_text_outcomes_label',
                  'label' => 'Title',
                  'name' => 'label',
                  'prefix' => '',
                  'type' => 'text',
                  'instructions' => 'e.g. You are a Lion Tamer!',
                  'required' => 1,
                  'conditional_logic' => array (
                      array (
                          array (
                              'field' => 'quiz_definition_quiz_type',
                              'operator' => '==',
                              'value' => 'text',
                          ),
                      ),
                  ),
                  'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'formatting' => 'html',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
              ),
              array (
                  'key' => 'quiz_definition_text_outcomes_description',
                  'label' => 'Description',
                  'name' => 'description',
                  'prefix' => '',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => array (
                      array (
                          array (
                              'field' => 'quiz_definition_quiz_type',
                              'operator' => '==',
                              'value' => 'text',
                          ),
                      ),
                  ),
                  'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 3,
                  'new_lines' => 'br',
                  'readonly' => 0,
                  'disabled' => 0,
              ),
              array (
                  'key' => 'quiz_definition_text_outcomes_image',
                  'label' => 'Image',
                  'name' => 'image',
                  'prefix' => '',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => array (
                      array (
                          array (
                              'field' => 'quiz_definition_quiz_type',
                              'operator' => '==',
                              'value' => 'text',
                          ),
                      ),
                  ),
                  'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                  ),
                  'preview_size' => 'thumbnail',
                  'library' => 'uploadedTo',
                  'return_format' => 'array',
                  'min_width' => 0,
                  'min_height' => 0,
                  'min_size' => 0,
                  'max_width' => 0,
                  'max_height' => 0,
                  'max_size' => 0,
                  'mime_types' => '',
              ),
          ),
      ),
      array (
          'key' => 'quiz_definition_questions',
          'label' => 'Questions',
          'name' => 'questions',
          'prefix' => '',
          'type' => 'repeater',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'row_min' => '',
          'row_limit' => '',
          'layout' => 'table',
          'button_label' => 'Add Question',
          'min' => 0,
          'max' => 0,
          'sub_fields' => array (
              array (
                  'key' => 'quiz_definition_questions_question',
                  'label' => 'Question',
                  'name' => 'question',
                  'prefix' => '',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'formatting' => 'html',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
              ),
              array (
                  'key' => 'quiz_definition_questions_answers',
                  'label' => 'Answers',
                  'name' => 'answers',
                  'prefix' => '',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                  ),
                  'row_min' => '',
                  'row_limit' => '',
                  'layout' => 'table',
                  'button_label' => 'Add Answer',
                  'min' => 0,
                  'max' => 0,
                  'sub_fields' => array (
                      array (
                          'key' => 'quiz_definition_questions_answers_answer_label',
                          'label' => 'Answer label',
                          'name' => 'answer_label',
                          'prefix' => '',
                          'type' => 'text',
                          'instructions' => '',
                          'required' => 1,
                          'conditional_logic' => 0,
                          'wrapper' => array (
                              'width' => '',
                              'class' => '',
                              'id' => '',
                          ),
                          'default_value' => '',
                          'placeholder' => '',
                          'prepend' => '',
                          'append' => '',
                          'formatting' => 'html',
                          'maxlength' => '',
                          'readonly' => 0,
                          'disabled' => 0,
                      ),
                      array (
                          'key' => 'quiz_definition_questions_answers_is_correct',
                          'label' => 'Is correct',
                          'name' => 'is_correct',
                          'prefix' => '',
                          'type' => 'true_false',
                          'instructions' => '',
                          'required' => 0,
                          'conditional_logic' => array (
                              array (
                                  array (
                                      'field' => 'quiz_definition_quiz_type',
                                      'operator' => '==',
                                      'value' => 'score',
                                  ),
                              ),
                          ),
                          'wrapper' => array (
                              'width' => '',
                              'class' => '',
                              'id' => '',
                          ),
                          'message' => '',
                          'default_value' => 0,
                      ),
                      array (
                          'key' => 'quiz_definition_questions_answers_text_outcome',
                          'label' => 'Text Outcome',
                          'name' => 'text_outcome',
                          'prefix' => '',
                          'type' => 'select',
                          'instructions' => '',
                          'required' => 0,
                          'conditional_logic' => array (
                              array (
                                  array (
                                      'field' => 'quiz_definition_quiz_type',
                                      'operator' => '==',
                                      'value' => 'text',
                                  ),
                              ),
                          ),
                          'wrapper' => array (
                              'width' => '',
                              'class' => '',
                              'id' => '',
                          ),
                          'choices' => array (
                              'none' => 'None',
                              1 => 1,
                              2 => 2,
                              3 => 3,
                              4 => 4,
                              5 => 5,
                              6 => 6,
                              7 => 7,
                              8 => 8,
                              9 => 9,
                              10 => 10,
                          ),
                          'default_value' => array (
                          ),
                          'allow_null' => 0,
                          'multiple' => 0,
                          'ui' => 0,
                          'ajax' => 0,
                          'placeholder' => '',
                          'disabled' => 0,
                          'readonly' => 0,
                      ),
                      array (
                          'key' => 'widget_quiz_questions_answers_image',
                          'label' => 'Image',
                          'name' => 'image',
                          'prefix' => '',
                          'type' => 'image',
                          'instructions' => '',
                          'required' => 0,
                          'conditional_logic' => 0,
                          'wrapper' => array (
                              'width' => '',
                              'class' => '',
                              'id' => '',
                          ),
                          'preview_size' => 'thumbnail',
                          'library' => 'all',
                          'return_format' => 'array',
                          'min_width' => 0,
                          'min_height' => 0,
                          'min_size' => 0,
                          'max_width' => 0,
                          'max_height' => 0,
                          'max_size' => 0,
                          'mime_types' => '',
                      ),
                  ),
              ),
              array (
                  'key' => 'widget_quiz_questions_image',
                  'label' => 'Image',
                  'name' => 'image',
                  'prefix' => '',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                  ),
                  'preview_size' => 'thumbnail',
                  'library' => 'uploadedTo',
                  'return_format' => 'array',
                  'min_width' => 0,
                  'min_height' => 0,
                  'min_size' => 0,
                  'max_width' => 0,
                  'max_height' => 0,
                  'max_size' => 0,
                  'mime_types' => '',
              ),
              array (
                  'key' => 'widget_quiz_questions_legacy_image',
                  'label' => 'Legacy image URL',
                  'name' => 'legacy_image',
                  'prefix' => '',
                  'type' => 'text',
                  'instructions' => 'Only use this with old-style quizzes',
                  'required' => 0,
                  'conditional_logic' => array (
                      array (
                          array (
                              'field' => 'quiz_definition_quiz_type',
                              'operator' => '==',
                              'value' => 'score',
                          ),
                      ),
                  ),
                  'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'formatting' => 'none',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
              ),
              array (
                  'key' => 'widget_quiz_questions_answer_information',
                  'label' => 'Answer Information',
                  'name' => 'answer_information',
                  'prefix' => '',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => array (
                      array (
                          array (
                              'field' => 'quiz_definition_quiz_type',
                              'operator' => '==',
                              'value' => 'score',
                          ),
                      ),
                  ),
                  'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => 'br',
                  'readonly' => 0,
                  'disabled' => 0,
              ),
          ),
      ),
  ),
  'location' => array (
      array (
          array (
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'quiz',
          ),
      ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
));


endif;
